import { parseEpubSourceInfo, parseSourceInfo } from '../yaml-utils';

describe('parseEpubSourceInfo', () => {
	it('parses current EPUB wikilinks', () => {
		const content = `---
we_source: '[[Books/demo.epub#weave-cfi=readium%3Aabc&chapter=3&text=Hello%20world|Demo]]'
---
Body`;

		expect(parseEpubSourceInfo(content)).toEqual({
			sourceFile: 'Books/demo.epub',
			cfi: 'readium:abc',
			text: 'Hello world',
			chapter: 3,
		});
	});

	it('parses legacy weave-epub protocol links', () => {
		const content = `---
we_source: '[EPUB来源](obsidian://weave-epub?vault=Vault&file=Books%2Fdemo.epub&cfi=epubcfi(/6/2)&text=Hello)'
---
Body`;

		expect(parseEpubSourceInfo(content)).toEqual({
			sourceFile: 'Books/demo.epub',
			cfi: 'epubcfi(/6/2)',
			text: 'Hello',
			chapter: undefined,
		});
	});

	it('finds EPUB sources inside we_source arrays', () => {
		const content = `---
we_source:
  - '[[notes/source.md]]'
  - '[[Books/demo.epub#weave-cfi=readium%3Axyz&chapter=5&text=Excerpt|Excerpt]]'
---
Body`;

		expect(parseEpubSourceInfo(content)).toEqual({
			sourceFile: 'Books/demo.epub',
			cfi: 'readium:xyz',
			text: 'Excerpt',
			chapter: 5,
		});
	});

	it('parses cfi-only EPUB wikilinks generated by the new default format', () => {
		const content = `---
we_source: '[[Books/demo.epub#weave-cfi=epubcfi(/6/34!/4/6,/1:0,/8:0)|Demo]]'
---
Body`;

		expect(parseEpubSourceInfo(content)).toEqual({
			sourceFile: 'Books/demo.epub',
			cfi: 'epubcfi(/6/34!/4/6,/1:0,/8:0)',
			text: '',
			chapter: undefined,
		});
	});

	it('finds the first valid markdown source inside we_source arrays', () => {
		const content = `---
we_source:
  - ''
  - '![[notes/source.md#^block-1]]'
---
Body`;

		expect(parseSourceInfo(content)).toEqual({
			sourceFile: 'notes/source.md',
			sourceBlock: 'block-1',
			refs: undefined,
		});
	});
});
